### ISSUE TITLE
How to use stdlib?

### ISSUE THREAD

**Issue by mantou132** [bhuztez/porus#4]
When I answered the [first question](https://leetcode.com/problems/two-sum/description/) of leetcode, a compile error occurred, the source code:

```rust
#![feature(proc_macro_non_items)]
#![cfg_attr(not(debug_assertions), no_std)]

#[macro_use]
extern crate porus;
use porus::prelude::*;

use std::collections::HashMap;

#[no_mangle]
pub extern "C" fn twoSum(nums: &[i32], numsSize: i32, target: i32) -> (usize, usize) {
  let mut map = HashMap::new();
  for (i, x) in nums.iter().enumerate() {
    let df = target - x;
    if map.contains_key(&df) {
      return (*map.get(&df).unwrap(), i);
    }
    map.insert(x, i);
  }
  return (0, 0);
}
```
output error:  `Maybe a missing `extern crate std;`?`

Then I try this:

```rust
#![feature(proc_macro_non_items)]

use std::collections::HashMap;

#[no_mangle]
pub extern "C" fn twoSum(nums: &[i32], numsSize: i32, target: i32) -> (usize, usize) {
  let mut map = HashMap::new();
  for (i, x) in nums.iter().enumerate() {
    let df = target - x;
    if map.contains_key(&df) {
      return (*map.get(&df).unwrap(), i);
    }
    map.insert(x, i);
  }
  return (0, 0);
}
```

output error:  `KeyError: 'submission_id'`.
filename is `1-two-sum.rs`

**Comment by bhuztez** [comment]
porus is intended to be an alternative to stdlib for competitive programming, since stdlib is too huge to be linked. Your second try failed because assembly code generated is too large to be accepted by Leetcode.

porus should have some alternatives to HashMap implemented. However, there isn't any right now, since porus is at very early stage of development.

**Comment by bhuztez** [comment]
You may try BTreeMap from `alloc` crate instead

```rust
#![feature(alloc)]
extern crate alloc;
extern crate porus;

use alloc::collections::BTreeMap;
use core::slice;

#[no_mangle]
pub extern "C" fn twoSum(nums: *const i32, numsSize: i32, target: i32) -> *const i32 {
  let mut map = BTreeMap::new();
  let s = unsafe { slice::from_raw_parts(nums, numsSize as usize) };

  for (i, x) in s.iter().enumerate() {
```

**Comment by bhuztez** [comment]
this has been solved in https://github.com/bhuztez/porus/blob/c5f18753a7c6faf6212acc50e4195ea53da9047a/examples/leetcode.com/two-sum.rs
